name: card_settings
description: A flutter package for building card based settings forms. This includes a library of pre-built form field widgets.
version: 3.5.2
homepage: https://github.com/codegrue/card_settings
issue_tracker: https://github.com/codegrue/card_settings/issues

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: any
  meta: any
  extended_masked_text: ^3.0.1

  # # Error: The getter 'subtitle2' isn't defined for the class 'TextTheme'.
  # # For main application, a temp workaround until card_settings repo merges it's own pubspect fix
  # dependency_overrides:
  #   flutter_cupertino_settings:
  #     git:
  #       url: https://github.com/imhafeez/flutter_cupertino_settings

  flutter_cupertino_settings: ^0.5.0 # show apple style dialogs
  flutter_material_pickers: ^3.7.0 # show android style dialogs
  pattern_formatter: ^4.0.0 # used for localized doubles
  flutter_multi_formatter: ^2.13.0 # used for localized phone numbers

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito: ^5.4.4

environment:
  sdk: ">=2.19.6 <4.0.0"

flutter:
  uses-material-design: true
